// Generated by CoffeeScript 2.6.1
// EnvLib.coffee
var hCallbacks;

import {
  strict as assert
} from 'assert';

import {
  undef
} from '@jdeighan/coffee-utils';

import {
  log
} from '@jdeighan/coffee-utils/log';

import {
  mkpath,
  slurp
} from '@jdeighan/coffee-utils/fs';

import {
  loadEnvFrom
} from '@jdeighan/env';

//     NOTE: use by:
//              1. call loadEnvLibFrom()
//              2. import hEnv and use directly
//     NOTE: keys are case sensitive
export var hEnv = {};

// ---------------------------------------------------------------------------
// Define custom callbacks to use with loadEnvFrom
hCallbacks = {
  getVar: function(name) {
    return hEnv[name];
  },
  setVar: function(name, value) {
    hEnv[name] = value;
  },
  clearVar: function(name) {
    delete hEnv[name];
  },
  clearAll: function() {
    var i, key, len, ref;
    ref = Object.keys(hEnv);
    for (i = 0, len = ref.length; i < len; i++) {
      key = ref[i];
      delete hEnv[name];
    }
  },
  names: function() {
    return Object.keys(hEnv);
  }
};

// ---------------------------------------------------------------------------
export var loadEnvLibFrom = function(searchDir, rootName = 'DIR_ROOT', hInit = {}) {
  hEnv = hInit; // reset, if there's been a previous call
  loadEnvFrom(searchDir, rootName, {hCallbacks});
  return hEnv;
};
